# Generated by Django 5.2.3 on 2025-06-16 22:23

import django.core.validators
import django.db.models.deletion
import secretariaescolar.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_choices', models.CharField(choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=50, null=True)),
                ('itinerary_choices', models.CharField(choices=[('DS', 'Desenvolvimento de Sistemas'), ('CN', 'Ciencias da Natureza'), ('JG', 'Desenvolvimento de Jogos')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_choices', models.CharField(choices=[('CH', 'Ciencias Humanas'), ('L', 'Linguagens'), ('M', 'Matematica'), ('CN', 'Ciencias da Natureza')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name="Professor's full name")),
                ('phone_number', models.CharField(max_length=15, validators=[secretariaescolar.validators.phone_validator], verbose_name="Professor's phone number (XX) 9XXXX-XXXX")),
                ('email', models.EmailField(max_length=100, verbose_name="Professor's email")),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[secretariaescolar.validators.cpf_validator], verbose_name="Professor's CPF")),
                ('birthday', models.DateField(max_length=10)),
                ('adress', models.CharField(max_length=100, validators=[secretariaescolar.validators.cep_validator])),
                ('class_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_class', to='secretariaescolar.class', verbose_name="Student's class")),
                ('matter_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_matter', to='secretariaescolar.matter', verbose_name="Student's matter")),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name="Student's full name")),
                ('registration_number', models.CharField(max_length=6, unique=True, verbose_name="Student's registration")),
                ('phone_number', models.CharField(max_length=15, validators=[secretariaescolar.validators.phone_validator], verbose_name="Student's phone number (XX) 9XXXX-XXXX")),
                ('email', models.EmailField(max_length=100, verbose_name="Student's email")),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[secretariaescolar.validators.cpf_validator], verbose_name="Student's CPF")),
                ('birthday', models.DateField(max_length=10)),
                ('adress', models.CharField(max_length=100, validators=[secretariaescolar.validators.cep_validator])),
                ('class_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='secretariaescolar.class', verbose_name="Student's class")),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name="Guardian's full name")),
                ('phone_number', models.CharField(max_length=15, validators=[secretariaescolar.validators.phone_validator], verbose_name="Guardian's phone number (XX) 9XXXX-XXXX")),
                ('email', models.EmailField(max_length=100, verbose_name="Guardian's email")),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[secretariaescolar.validators.cpf_validator], verbose_name="Guardian's CPF")),
                ('birthday', models.DateField(max_length=10)),
                ('adress', models.CharField(max_length=100, validators=[secretariaescolar.validators.cep_validator])),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_student', to='secretariaescolar.student', verbose_name="Guardian's student")),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_pdf', models.FileField(blank=True, null=True, upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('guardian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_guardian', to='secretariaescolar.guardian', verbose_name="Guardian's name")),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_student', to='secretariaescolar.student', verbose_name="Student's name")),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_presence', models.FloatField(default=0, validators=[secretariaescolar.validators.validate_nota], verbose_name='Grade of Presence')),
                ('grade_activity', models.FloatField(default=0, validators=[secretariaescolar.validators.validate_nota], verbose_name='Grade of Activity')),
                ('grade_evaluative', models.FloatField(default=0, validators=[secretariaescolar.validators.validate_nota], verbose_name='Grade of Evaluative')),
                ('grade_final', models.FloatField(default=0, editable=False, validators=[secretariaescolar.validators.validate_nota], verbose_name='Final Grade')),
                ('classs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_class', to='secretariaescolar.class', verbose_name='class')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_matter', to='secretariaescolar.matter', verbose_name='matter')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to='secretariaescolar.student', verbose_name='student')),
            ],
            options={
                'unique_together': {('student', 'classs', 'matter')},
            },
        ),
    ]
