# Generated by Django 5.2.3 on 2025-06-17 01:52

import django.core.validators
import django.db.models.deletion
import secretariaescolar.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariaescolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='matter',
            options={'verbose_name': 'Área/Disciplina', 'verbose_name_plural': 'Áreas/Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_choices',
            field=models.CharField(choices=[('1A', '1º Ano A'), ('1B', '1º Ano B'), ('1C', '1º Ano C'), ('2A', '2º Ano A'), ('2B', '2º Ano B'), ('2C', '2º Ano C'), ('3A', '3º Ano A'), ('3B', '3º Ano B'), ('3C', '3º Ano C')], max_length=50, null=True, verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='class',
            name='itinerary_choices',
            field=models.CharField(choices=[('DS', 'Desenvolvimento de Sistemas'), ('CN', 'Ciências da Natureza'), ('JG', 'Desenvolvimento de Jogos')], max_length=50, null=True, verbose_name='Itinerário'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_guardian', to='secretariaescolar.guardian', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_student', to='secretariaescolar.student', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='uploaded_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Contrato em PDF'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='classs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_class', to='secretariaescolar.class', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_activity',
            field=models.FloatField(default=0, validators=[secretariaescolar.validators.validate_nota], verbose_name='Nota de Atividade'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_evaluative',
            field=models.FloatField(default=0, validators=[secretariaescolar.validators.validate_nota], verbose_name='Nota Avaliativa'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_final',
            field=models.FloatField(default=0, editable=False, validators=[secretariaescolar.validators.validate_nota], verbose_name='Nota Final'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_presence',
            field=models.FloatField(default=0, validators=[secretariaescolar.validators.validate_nota], verbose_name='Nota de Presença'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_matter', to='secretariaescolar.matter', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to='secretariaescolar.student', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='adress',
            field=models.CharField(max_length=100, validators=[secretariaescolar.validators.cep_validator], verbose_name='Endereço do responsável'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='birthday',
            field=models.DateField(max_length=10, verbose_name='Data de nascimento do responsável'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[secretariaescolar.validators.cpf_validator], verbose_name='CPF do responsável'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail do responsável'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='full_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome completo do responsável'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[secretariaescolar.validators.phone_validator], verbose_name='Telefone do responsável (XX) 9XXXX-XXXX'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_student', to='secretariaescolar.student', verbose_name='Aluno do responsável'),
        ),
        migrations.AlterField(
            model_name='matter',
            name='matter_choices',
            field=models.CharField(choices=[('CH', 'Ciências Humanas'), ('L', 'Linguagens'), ('M', 'Matemática'), ('CN', 'Ciências da Natureza')], max_length=50, null=True, verbose_name='Área da disciplina'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='adress',
            field=models.CharField(max_length=100, validators=[secretariaescolar.validators.cep_validator], verbose_name='Endereço do professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='birthday',
            field=models.DateField(max_length=10, verbose_name='Data de nascimento do professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_class', to='secretariaescolar.class', verbose_name='Turma do professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[secretariaescolar.validators.cpf_validator], verbose_name='CPF do professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail do professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='full_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome completo do professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='matter_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_matter', to='secretariaescolar.matter', verbose_name='Disciplina do professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[secretariaescolar.validators.phone_validator], verbose_name='Telefone do professor (XX) 9XXXX-XXXX'),
        ),
        migrations.AlterField(
            model_name='student',
            name='adress',
            field=models.CharField(max_length=100, validators=[secretariaescolar.validators.cep_validator], verbose_name='Endereço do aluno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(max_length=10, verbose_name='Data de nascimento do aluno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='secretariaescolar.class', verbose_name='Turma do aluno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[secretariaescolar.validators.cpf_validator], verbose_name='CPF do aluno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail do aluno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome completo do aluno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[secretariaescolar.validators.phone_validator], verbose_name='Telefone do aluno (XX) 9XXXX-XXXX'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=6, unique=True, verbose_name='Matrícula do aluno'),
        ),
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da advertência')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertencias', to='secretariaescolar.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Advertência',
                'verbose_name_plural': 'Advertências',
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da falta')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='secretariaescolar.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'Faltas',
            },
        ),
        migrations.CreateModel(
            name='Suspensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da suspensão')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('dias', models.PositiveIntegerField(verbose_name='Dias de suspensão')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes', to='secretariaescolar.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Suspensão',
                'verbose_name_plural': 'Suspensões',
            },
        ),
    ]
