# Generated by Django 5.2.3 on 2025-06-17 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariaescolar', '0002_alter_class_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data', models.DateTimeField(verbose_name='Data e hora')),
                ('tipo', models.CharField(choices=[('prova', 'Prova'), ('feriado', 'Feriado'), ('reuniao', 'Reunião'), ('entrega', 'Entrega de Trabalho'), ('atividade', 'Atividade'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de evento')),
                ('publico_alvo', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('todos', 'Todos')], default='todos', max_length=20, verbose_name='Público alvo')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_prof', to='secretariaescolar.professor', verbose_name='Professor')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='secretariaescolar.class', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
